from . import student_level
from . import education_relationship
from . import student_relation
from . import education_student
from . import res_partner
from . import education_class_group
from . import education_class
from . import education_school
from . import education_school_year
from . import student_school_stage
from . import res_config_settings
