{
    "name": "Healthy Care Theme",
    "name_vi_VN": "Chủ đề cho website chăm sóc sức khỏe",
    "summary": "Theme, Layout, Snippets for website healthy care",
    "summary_vi_VN": "Chủ đề, snippet cho website chăm sóc sức khỏe",
    "description": "Theme for website healthy care",
    "description_vi_VN": "Chủ đề cho website chăm sóc sức khỏe",
    "author": "Viindoo",
    "website": "https://viindoo.com/",
    "live_test_url": "https://viindoo.com",
    "support": "apps.support@viindoo.com",
    "category": "Theme/Services",
    "sequence": 120,
    "version": "0.1",
    'depends': ['viin_theme_common'],
    'data': [
        'data/ir_asset.xml',
        'views/images_library.xml',
        
        'views/snippets/s_title.xml',
        'views/snippets/s_media_list.xml',
        'views/snippets/s_image_text.xml',
        'views/snippets/s_product_list.xml',
        'views/snippets/s_picture.xml',
    ],
    'images': [
        'static/description/theme_viin_healthy_care_preview.jpeg',
    ],
    'images_preview_theme': {
        "website.s_cover_default_image":"/theme_viin_healthy_care/static/src/img/snippets/s_cover.jpg",
        "website.s_masonry_block_default_image_1":"/theme_viin_healthy_care/static/src/img/snippets/s_masonry_block.jpg",
        "website.s_media_list_default_image_1":"/theme_viin_healthy_care/static/src/img/snippets/img_media_list/s_media_list_1.jpg",
        "website.s_media_list_default_image_2":"/theme_viin_healthy_care/static/src/img/snippets/img_media_list/s_media_list_2.jpg",
        "website.s_media_list_default_image_3":"/theme_viin_healthy_care/static/src/img/snippets/img_media_list/s_media_list_3.jpg",
        "website.s_quotes_carousel_demo_image_1":"/theme_viin_healthy_care/static/src/img/snippets/s_quotes_carousel_demo_1.jpg",
        "website.s_quotes_carousel_demo_image_2":"/theme_viin_healthy_care/static/src/img/snippets/s_quotes_carousel_demo_2.jpg",
        "website.s_carousel_default_image_1":"/theme_viin_healthy_care/static/src/img/snippets/s_carousel_1.jpg",
        "website.s_carousel_default_image_2":"/theme_viin_healthy_care/static/src/img/snippets/s_carousel_2.jpg",
        "website.s_carousel_default_image_3":"/theme_viin_healthy_care/static/src/img/snippets/s_carousel_3.jpg",
        "website.s_banner_default_image":"/theme_viin_healthy_care/static/src/img/snippets/s_carousel_1.jpg",
        "website.s_parallax_default_image":"/theme_viin_healthy_care/static/src/img/snippets/s_parallax.jpg",
        "website.s_product_catalog_default_image":"/theme_viin_healthy_care/static/src/img/snippets/s_product_catalog.jpg",
        "website.s_product_list_default_image_1":"/theme_viin_healthy_care/static/src/img/snippets/img_feature/s_feature_1.jpg",
        "website.s_product_list_default_image_2":"/theme_viin_healthy_care/static/src/img/snippets/img_feature/s_feature_2.jpg",
        "website.s_product_list_default_image_3":"/theme_viin_healthy_care/static/src/img/snippets/img_feature/s_feature_3.jpg",
        "website.s_product_list_default_image_4":"/theme_viin_healthy_care/static/src/img/snippets/img_feature/s_feature_4.jpg",
        "website.s_product_list_default_image_5":"/theme_viin_healthy_care/static/src/img/snippets/img_feature/s_feature_5.jpg",
        "website.s_product_list_default_image_6":"/theme_viin_healthy_care/static/src/img/snippets/img_feature/s_feature_6.jpg",
        "website.s_picture_default_image":"/theme_viin_healthy_care/static/src/img/snippets/img_picture/s_picture_1.jpg",
        "website.s_image_text_default_image":"/theme_viin_healthy_care/static/src/img/snippets/s_image_text.jpg",
        "website.s_text_image_default_image":"/theme_viin_healthy_care/static/src/img/snippets/s_text_image.jpg",
        "website.s_three_columns_default_image_1":"/theme_viin_healthy_care/static/src/img/snippets/s_three_columns_1.jpg",
        "website.s_three_columns_default_image_2":"/theme_viin_healthy_care/static/src/img/snippets/s_three_columns_2.jpg",
        "website.s_three_columns_default_image_3":"/theme_viin_healthy_care/static/src/img/snippets/s_three_columns_3.jpg",
        "website.s_quotes_carousel_demo_image_0":"/theme_viin_healthy_care/static/src/img/snippets/s_quotes_carousel_demo_0.jpg",
        "website.library_image_03":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/s_img_wall_3.jpg",
        "website.library_image_10":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/s_img_wall_4.jpg",
        "website.library_image_13":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/s_img_wall_2.jpg",
        "website.library_image_05":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/s_img_wall_5.jpg",
        "website.library_image_14":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/s_img_wall_6.jpg",
        "website.library_image_16":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/s_img_wall_1.jpg",
        "website.library_image_08":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/library_image_08.jpg",
        "website.library_image_02":"/theme_viin_healthy_care/static/src/img/snippets/img_gallery/library_image_02.jpg"
    },
    'snippet_lists': {
        'homepage': ['s_carousel', 's_images_wall', 's_text_image','s_three_columns', 's_image_text'],
    },
    'price': 0.0,
    'currency': 'EUR',
    'license': 'OPL-1'
}
