{
    "name": "Houseware Ecommerce Viindoo Theme",
    "name_vi_VN": "Chủ đề cho website đồ dùng gia dụng cho thương mại điện tử",
    "summary": "Theme, Layout, Snippets for website ecommerce houseware",
    "summary_vi_VN": "Chủ đề, bố cục, snippet cho website đồ gia dụng cho thương mại điện tử",
    "description": "Theme for website ecommerce houseware",
    "description_vi_VN": "Chủ đề cho website đồ gia dụng cho thương mại điện tử",
    "author": "Viindoo",
    "website": "https://viindoo.com/",
    "live_test_url": "https://viindoo.com",
    "support": "apps.support@viindoo.com",
    "category": "Theme/Ecommerce",
    "sequence": 120,
    "version": "0.1",
    'depends': ['website_sale', 'viindoo_theme_common'],
    'data': [
        'data/ir_asset.xml',
        'views/image_library.xml',
        
        'views/snippets/s_carousel.xml',
        'views/snippets/s_cover.xml',
        'views/snippets/s_product_list.xml',
        'views/snippets/s_feature.xml',
        'views/snippets/s_text_image.xml',
        'views/snippets/s_title.xml',
        'views/snippets/s_big_box.xml',
        'views/snippets/s_banner.xml',
        'views/snippets/s_image_text.xml',
        'views/snippets/s_image_gallery.xml',
        'views/snippets/s_numbers.xml',
        'views/snippets/s_three_columns.xml',
        'views/snippets/s_call_to_action.xml'
    ],
    'images': [
        'static/description/theme_ecommerce_houseware.jpeg',
    ],
    'price': 0.0,
    'currency': 'EUR',
    'license': 'OPL-1',
}
