{
    "name": "Fashion Ecomerce Viindoo Theme",
    "name_vi_VN": "Chủ đề cho website thời trang thương mại điện tử",
    "summary": "themes, snippets, layouts, images, content for fashion websites",
    "summary_vi_VN": "chủ đề, đoạn trích, bố cục, hình ảnh, nội dung cho trang web về thời trang",
    
    'industries': """
    fashion, clothes, footwear
""",

    "description": "Theme for website ecommerce fashion",
    "description_vi_VN": "Chủ đề cho website thời trang thương mại điện tử",
    "author": "Viindoo",
    "website": "https://viindoo.com/",
    "live_test_url": "https://viindoo.com",
    "support": "apps.support@viindoo.com",
    "category": "Ecommerce",
    "sequence": 120,
    "version": "0.1",
    'depends': ['viin_theme_common'],
    'data': [
        'data/ir_asset.xml',
        'views/image_library.xml',
        
        'views/snippets/s_carousel.xml',
        'views/snippets/s_image_wall.xml',
        'views/snippets/s_features.xml',
        'views/snippets/s_picture.xml',
        'views/snippets/s_title.xml',
        'views/snippets/s_three_columns.xml',
        'views/snippets/s_references.xml',
        'views/snippets/s_countdown.xml',
        'views/snippets/s_product_list.xml',
        'views/snippets/s_call_to_action.xml'
    ],
    'images': [
        'static/description/viin_ecommerce_fashion.jpeg',
    ],
    'images_preview_theme': {
        "website.s_cover_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_cover.jpeg",
        "website.s_masonry_block_default_image_1":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_masonry_block.jpeg",
        "website.s_media_list_default_image_1":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_media_list_1.jpeg",
        "website.s_media_list_default_image_2":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_media_list_2.jpeg",
        "website.s_media_list_default_image_3":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_media_list_3.jpeg",
        "website.s_quotes_carousel_demo_image_1":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_quotes_carousel_1.jpeg",
        "website.s_quotes_carousel_demo_image_2":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_quotes_carousel_2.jpeg",
        "website.s_carousel_default_image_1":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_carousel_1.jpeg",
        "website.s_carousel_default_image_2":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_carousel_2.jpeg",
        "website.s_carousel_default_image_3":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_carousel_3.jpeg",
        "website.s_banner_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_banner.jpeg",
        "website.s_parallax_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_parallax.jpeg",
        "website.s_product_catalog_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_catalog.jpeg",
        "website.s_product_list_default_image_1":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_1.jpeg",
        "website.s_product_list_default_image_2":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_2.jpeg",
        "website.s_product_list_default_image_3":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_3.jpeg",
        "website.s_product_list_default_image_4":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_4.jpeg",
        "website.s_product_list_default_image_5":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_5.jpeg",
        "website.s_product_list_default_image_6":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_product_6.jpeg",
        "website.s_picture_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_picture_default_image.jpeg",
        "website.s_image_text_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_image_text.jpeg",
        "website.s_text_image_default_image":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_text_image.jpeg",
        "website.s_three_columns_default_image_1":"/theme_viin_ecommerce_fashion/static/src/img/content/s_three_columns_1.jpeg",
        "website.s_three_columns_default_image_2":"/theme_viin_ecommerce_fashion/static/src/img/content/s_three_columns_2.jpeg",
        "website.s_three_columns_default_image_3":"/theme_viin_ecommerce_fashion/static/src/img/content/s_three_columns_3.jpeg",
        "website.s_quotes_carousel_demo_image_0":"/theme_viin_ecommerce_fashion/static/src/img/snippets/s_quotes_carousel_0.jpeg",
        "website.library_image_03":"/theme_viin_ecommerce_fashion/static/src/img/snippets/library_image_03.jpeg",
        "website.library_image_10":"/theme_viin_ecommerce_fashion/static/src/img/snippets/library_image_10.jpeg",
        "website.library_image_13":"/theme_viin_ecommerce_fashion/static/src/img/snippets/library_image_13.jpeg",
        "website.library_image_05":"/theme_viin_ecommerce_fashion/static/src/img/snippets/library_image_05.jpeg",
        "website.library_image_14":"/theme_viin_ecommerce_fashion/static/src/img/snippets/library_image_14.jpeg",
        "website.library_image_16":"/theme_viin_ecommerce_fashion/static/src/img/snippets/library_image_16.jpeg",
        "website.library_image_08":"/theme_viin_ecommerce_fashion/static/src/img/content/library_image_08.jpeg",
        "website.library_image_02":"/theme_viin_ecommerce_fashion/static/src/img/content/library_image_02.jpeg"
    },
    'snippet_lists': {
        'homepage': ['s_carousel', 's_images_wall', 's_countdown','s_features', 's_media_list', 's_numbers', 's_title', 's_three_columns'],
    },
    "price": 0.0,
    "currency": "EUR",
    "license": "OPL-1"
}
