{
    "name": "Electronics Manufacturing Viindoo Theme",
    "name_vi_VN": "Chủ đề cho website sản xuất phụ kiện điện tử",
    "summary": "Theme, Layout, Snippets for website manufacturing electronics",
    "summary_vi_VN": "Chủ đề, snippet cho website sản xuất phụ kiện điện tử",
    "description": "Theme, Layout, snippets for website manufacturing security camera(CCVT)",
    "description_vi_VN": "Chủ đề, bốc cục, snippets cho website doanh nghiệp sản xuất camera an ninh",
    "author": "Viindoo",
    "website": "https://viindoo.com/",
    "live_test_url": "https://viindoo.com",
    "support": "apps.support@viindoo.com",
    'category': 'Theme/Corporate',
    "sequence": 20,
    "version": "0.1",
    'depends': ['website_hr_recruitment', 'viindoo_theme_common'],
    'data': [
        'data/website_menu.xml',
        'data/ir_asset.xml',       
        'views/images_library.xml',
        
        'views/snippets/s_cover.xml',
        'views/snippets/s_banner.xml',
        'views/snippets/s_carousel.xml',
        'views/snippets/s_image_text.xml',
        'views/snippets/s_text_image.xml',
        'views/snippets/s_color_blocks_2.xml',
        'views/snippets/s_media_list.xml',
        'views/snippets/s_image_gallery.xml',
        'views/snippets/s_image_wall.xml',
        'views/snippets/s_title.xml',
        'views/snippets/s_features.xml',
        'views/snippets/s_references.xml',
        'views/snippets/s_features_grid.xml',
        'views/snippets/s_showcase.xml',
        'views/snippets/s_numbers.xml',
        'views/snippets/s_call_to_action.xml',
        'views/snippets/s_product_list.xml',
        'views/snippets/s_masonry_block.xml',
    ],
    'images': [
        'static/description/theme_manufaturing_electronics_screen_shot.jpeg',
    ],
    'price': 0.0,
    'currency': 'EUR',
    'license': 'OPL-1',
}
